version: '3'
networks:
  mastodon_network:
    external: true
services:
  db:
    container_name: mastodon-db
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    networks:
      - mastodon_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    env_file:
      - .env.db