version: '3'
networks:
  mastodon_network:
    external: true
services:
  redis:
    container_name: mastodon-redis  
    restart: always
    image: redis:7-alpine
    networks:
      - mastodon_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./data/redis:/data